# Generated by Django 3.0.6 on 2020-05-12 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_by',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Customer'),
        ),
    ]
